apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: 2276719381991.dkr.ecr.ap-south-1.amazonaws.com/dev/my-backend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 3500

        env:
        - name: MONGO_CONN_STR
          value: mongodb://mongodb:27017/todo